### ISSUE TITLE
2021/09/01（三）每月例行維護

### ISSUE THREAD

**Issue by jason920612** [jason920612/YingLingdom-Network-Minecraft-Server#2]
明 2021/09/01（三）將進行每月例行維護
維護時間：10:00 至 15:00
維護完成將另行公告

本次預計更改：
１. UI更動
２. 區塊優化
３. 經濟系統初步上線
......等
　
預定明日下午四點公告幽靈警戒名單

**Comment by KageRyo** [comment]
維護完成，issues應該被關閉。
